name:                ultimate-tic-tac-toe
version:             0.1.0.0
git:                 "https://github.students.cs.ubc.ca/tchen66/cpsc312-project1.git"
license:             BSD-3-Clause
author:              ["Jerry Zhang", "Tony Chen", "Junming Ge"]
copyright:           "2024 Jerry Zhang, Tony Chen, and Junming Ge"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.students.cs.ubc.ca/tchen66/cpsc312-project1#readme>

dependencies:
- base >= 4.7 && < 5
- Cabal
- random

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  ultimate-tic-tac-toe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ultimate-tic-tac-toe
